
service: census
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

provider:
  name: aws
  runtime: nodejs10.x


stage: dev
region: us-east-1
role: arn:aws:iam::068764338046:role/serverlessdemo-dev-us-east-1-lambdaRole


# Define Environment Variables...
#  environment:
#    variable1: value1

# Packaging Information
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:

  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          cors: true
  
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: /users
          method: post
          cors: true

# Plugins
plugins:
  - serverless-offline  